sources += files(
    'installation-workflow.vala',
    'archive-workflow-support.vala',
    'steam-tinker-launch-context.vala',
    'install-job.vala',
    'standard-archive-workflow.vala',
    'steam-tinker-launch-workflow.vala',
    'installation-service.vala',
    'steam-session-service.vala',
)

subdir('migrations')
