sources += files(
    'cpu-probe.c',
    'archive-helper.vala',
    'filesystem.vala',
    'web.vala',
    'parser.vala',
    'metadata.vala',
    'system.vala',
    'i18n.vala',
    'controller-input-policy.vala',
    'controller-surface-policy.vala',
    'controller-manager.vala',
    'theme-manager.vala',
    'download-manager.vala',
    'mangohud-manager.vala',
    'cache-manager.vala',
)

subdir('internal')
subdir('vdf')
