sources += files(
    'cpu-capabilities.vala',
    'variant-compatibility.vala',
    'group.vala',
    'compatibility-tool.vala',
    'installed-tool-inventory.vala',
    'steam-profile.vala',
    'launcher.vala',
    'release.vala',
    'release-catalog-cache.vala',
    'release-catalog-result.vala',
    'release-catalog.vala',
    'tool.vala',
    'game.vala',
    'variant.vala',
)

subdir('games')
subdir('assets')
subdir('internal')
subdir('launchers')
subdir('providers')
subdir('tools')
subdir('steam')
