namespace ProtonPlus {
    public enum ReturnCode {
		UNKNOWN_ERROR,
		RELEASES_LOADED,
		NOTHING_TO_UPDATE,
		RUNNERS_UPDATED,
		RUNNER_UPDATED,
		VALID_REQUEST,
		CONNECTION_ISSUE,
		CONNECTION_REFUSED,
		CONNECTION_UNKNOWN,
		API_LIMIT_REACHED,
		INVALID_ACCESS_TOKEN,
	}
}