sources += files(
    'application.vala',
    'controller-choice-box.vala',
    'controller-hint-bar.vala',
    'window.vala',
    'circular-progress-bar.vala',
)

subdir('preferences')
subdir('header')
subdir('introduction')
subdir('loading')
subdir('main')
subdir('tools')
subdir('games')
subdir('mangohud')
