name: Build & Check

on: 
  pull_request:
    branches:
    - main

jobs:
  flatpak-build:
    name: "Flatpak Build"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - name: Checkout pull request
      uses: actions/checkout@v4
    - name: Build
      uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: protonplus.flatpak
        manifest-path: com.vysp3r.ProtonPlus.local.yml
        cache-key: flatpak-builder-${{ github.sha }}
